modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="intelligencetweaks"
version="1.0"
displayName="Intelligence Tweaks"
displayURL="https://srendi.de/"
authors="Sr_endi"
description='''
Intelligence Tweaks is a mod made for my Modpacks. It increases the maximum packet size from 2MB to 1GB.

'''
[[dependencies.intelligencetweaks]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.intelligencetweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4)"
    ordering="NONE"
    side="BOTH"
