modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="intelligencetweaks"
version="0.1.2b"
displayName="Intelligence Tweaks"
displayURL="https://srendi.de/"
authors="Sr_endi"
description='''
Intelligence Tweaks is a mod made for my Modpacks.

'''
[[dependencies.intelligencetweaks]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.intelligencetweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5)"
    ordering="NONE"
    side="BOTH"
